export const statusInitialSnapshot = {
    system_on:0,
    silenced_led:0,
    mains_fault_led:0,
    battery_fault_led:0,
    system_fault: 0,
    NAC_fault: 0,
    manual_release: 0,
    pre_release: 0,
    released_led:0,
    abort_led:0,
    pressure_fault_led:0,
    RAC_fault_led:0,
    earth_fault_led:0,
    maintenance_led:0,
    disabled_led: 0,
    test_led: 0,
    delay_led: 0,
    fire: 0,
    general_fault: 0,
    // system_fault: 0,
    function1_led: 0,
    function2_led: 0,
    sounder_dis_fau: 0,
    routing_fau_dis: 0,
    alarm_routing: 0,
    more_alarm: 0,
    reserved:0,
    device_status:0
};
